import json
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import numpy as np
import pandas as pd
from dexfcl.paper_outputs import load_archive, write_tables
from dexfcl.reporting import aggregate_results

ROOT = Path(__file__).resolve().parents[1]


class PaperOutputTests(unittest.TestCase):
    def test_cli_exports_complete_figure_set_and_source_hashes(self):
        with tempfile.TemporaryDirectory() as tmp:
            t=Path(tmp)/'tables';f=Path(tmp)/'figures'
            env=os.environ.copy();env['PYTHONPATH']=str(ROOT/'src')
            subprocess.run([sys.executable,'-m','dexfcl','reproduce-paper','--results',str(ROOT/'results'),
                            '--tables',str(t),'--figures',str(f)],check=True,capture_output=True,env=env)
            manifest=json.loads((t/'paper_outputs_manifest.json').read_text())
            self.assertFalse(manifest['training_provenance_verified'])
            for name,h in manifest['source_sha256'].items():
                self.assertEqual(hashlib.sha256((ROOT/'results'/name).read_bytes()).hexdigest(),h)
            names={p.stem for p in (ROOT/'results/figures').glob('*.png')}
            for suffix in ['png','pdf','eps']:
                self.assertEqual({p.stem for p in f.glob(f'*.{suffix}')},names)
                for p in f.glob(f'*.{suffix}'):
                    self.assertGreater(p.stat().st_size,100)
                    if suffix=='png':self.assertEqual(p.read_bytes()[:8],b'\x89PNG\r\n\x1a\n')

    def test_scientific_summaries_match_archived_tables(self):
        frames = load_archive(ROOT / 'results')
        with tempfile.TemporaryDirectory() as tmp:
            write_tables(frames, tmp)
            for kind in ['primary', 'continual', 'explanation', 'assimilation', 'ablation']:
                keys = ['dataset', 'method'] if kind in {'primary','continual','explanation'} else ['dataset', 'shots' if kind=='assimilation' else 'configuration']
                old = pd.read_csv(ROOT/'results'/f'table_{kind}_summary.csv', header=[0,1], index_col=[0,1])
                new = pd.read_csv(Path(tmp)/f'table_{kind}_summary.csv').set_index(keys)
                for metric, stat in old.columns:
                    col = f'{metric}_{stat}'
                    if col not in new:  # Historical timing is not regenerated by training.
                        continue
                    np.testing.assert_allclose(new.loc[old.index,col],old[(metric,stat)],rtol=1e-12,atol=1e-14)

    def test_missing_seed_and_duplicate_are_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            r=Path(tmp)/'results';shutil.copytree(ROOT/'results',r)
            p=r/'primary_runs.csv';d=pd.read_csv(p);d.iloc[1:].to_csv(p,index=False)
            with self.assertRaisesRegex(ValueError,'incomplete seeds'):load_archive(r)
            pd.concat([d,d.iloc[[0]]]).to_csv(p,index=False)
            with self.assertRaisesRegex(ValueError,'duplicate'):load_archive(r)

    def test_missing_experiment_level_and_nan_are_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            r=Path(tmp)/'results';shutil.copytree(ROOT/'results',r)
            p=r/'noniid_runs.csv';d=pd.read_csv(p);d[d.alpha!=0.1].to_csv(p,index=False)
            with self.assertRaisesRegex(ValueError,'incomplete alpha'):load_archive(r)
            d.to_csv(p,index=False)
            p=r/'primary_runs.csv';d=pd.read_csv(p);d.loc[0,'macro_f1']=np.nan;d.to_csv(p,index=False)
            with self.assertRaisesRegex(ValueError,'non-finite'):load_archive(r)

    def test_aggregate_archive_and_mixed_source_guard(self):
        with tempfile.TemporaryDirectory() as tmp:
            r=Path(tmp)/'results';shutil.copytree(ROOT/'results',r)
            frames=aggregate_results(r,Path(tmp)/'tables')
            self.assertEqual(len(frames['ablation']),50)
            (r/'closed_ciciot2023_seed7.csv').write_text('placeholder')
            with self.assertRaisesRegex(ValueError,'Both archived and campaign'):aggregate_results(r,Path(tmp)/'tables')
            self.assertEqual(len(aggregate_results(r,Path(tmp)/'tables','archived')['primary']),50)

    def test_sampling_is_repeatable_exact_and_does_not_overwrite_input(self):
        with tempfile.TemporaryDirectory() as tmp:
            r=Path(tmp);source=r/'source.csv'
            source.write_text('Attack_type,value\n'+''.join(f'{c},{i}\n' for c,n in [('Normal',37),('Attack',63)] for i in range(n)))
            before=source.read_bytes();outputs=[]
            for k in [1,2]:
                out=r/f'nested{k}'/'sample.csv'
                subprocess.run([sys.executable,str(ROOT/'scripts/make_edgeiiot_10pct.py'),str(source),'--output',str(out)],check=True,capture_output=True)
                outputs.append(out.read_bytes())
                m=json.loads(out.with_suffix('.csv.manifest.json').read_text())
                self.assertEqual(m['selected_counts'],{'Attack':6,'Normal':4})
                self.assertEqual(m['output_rows'],10)
            self.assertEqual(outputs[0],outputs[1]);self.assertEqual(before,source.read_bytes())
            for extra in [['--fraction','1.1'],['--output',str(source)]]:
                result=subprocess.run([sys.executable,str(ROOT/'scripts/make_edgeiiot_10pct.py'),str(source),*extra],capture_output=True)
                self.assertNotEqual(result.returncode,0)
                self.assertEqual(before,source.read_bytes())


if __name__=='__main__':unittest.main()
